#!/usr/bin/env python 

import argparse
import sys

import yaml

from crowsnest import config

parser = argparse.ArgumentParser()
parser.add_argument("--config", help="Config file")

args = parser.parse_args()

config._setup_node_defaults()

if args.config:
	with open(args.config, 'r') as f:
		_config = yaml.load(f)
		for key in _config:
			_dict = getattr(config, key)
			_dict.update(_config[key])
			setattr(config, key, _dict)

from crowsnest.node import manager
_manager = manager.Manager()