gui:
  host: 0.0.0.0
  port: 80
api:
  host: 0.0.0.0
  port: 8080
database:
  name: crowsnest
  host: 10.0.0.1
  port: 27017
sniffer:
  ifname: h3-eth0
  protocol: tcp
  port: 80
sessions:
  expirey_time: 10